# Generated by Django 4.2.27 on 2026-02-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
